# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\xampp\htdocs\tds\TDS-exercises\semestre-4\python\QT\caixa_mensagem.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 525)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(30, 20, 331, 451))
        self.groupBox.setObjectName("groupBox")
        self.btadicionar = QtWidgets.QPushButton(self.groupBox)
        self.btadicionar.setGeometry(QtCore.QRect(10, 230, 75, 23))
        self.btadicionar.setObjectName("btadicionar")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 30, 51, 31))
        self.label.setObjectName("label")
        self.leNome = QtWidgets.QLineEdit(self.groupBox)
        self.leNome.setGeometry(QtCore.QRect(60, 30, 113, 31))
        self.leNome.setStyleSheet("background:\n"
"    rgb(170, 0, 0);")
        self.leNome.setObjectName("leNome")
        self.btexcluir = QtWidgets.QPushButton(self.groupBox)
        self.btexcluir.setGeometry(QtCore.QRect(10, 310, 75, 23))
        self.btexcluir.setObjectName("btexcluir")
        self.btfechar = QtWidgets.QPushButton(self.groupBox)
        self.btfechar.setGeometry(QtCore.QRect(150, 420, 75, 23))
        self.btfechar.setObjectName("btfechar")
        self.btordenar = QtWidgets.QPushButton(self.groupBox)
        self.btordenar.setGeometry(QtCore.QRect(10, 270, 75, 23))
        self.btordenar.setObjectName("btordenar")
        self.lista = QtWidgets.QListWidget(self.groupBox)
        self.lista.setGeometry(QtCore.QRect(95, 230, 201, 181))
        self.lista.setObjectName("lista")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(230, 420, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 420, 31, 16))
        self.label_2.setObjectName("label_2")
        self.lbconta = QtWidgets.QLabel(self.groupBox)
        self.lbconta.setGeometry(QtCore.QRect(50, 420, 47, 13))
        self.lbconta.setText("")
        self.lbconta.setObjectName("lbconta")
        self.leIdade = QtWidgets.QLineEdit(self.groupBox)
        self.leIdade.setGeometry(QtCore.QRect(252, 30, 51, 31))
        self.leIdade.setStyleSheet("background:\n"
"    rgb(170, 0, 0);")
        self.leIdade.setObjectName("leIdade")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(220, 30, 31, 31))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(10, 80, 47, 13))
        self.label_6.setObjectName("label_6")
        self.rb1 = QtWidgets.QRadioButton(self.groupBox)
        self.rb1.setGeometry(QtCore.QRect(80, 80, 82, 17))
        self.rb1.setObjectName("rb1")
        self.rb2 = QtWidgets.QRadioButton(self.groupBox)
        self.rb2.setGeometry(QtCore.QRect(170, 80, 82, 17))
        self.rb2.setObjectName("rb2")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(10, 130, 61, 16))
        self.label_7.setObjectName("label_7")
        self.cbnivel = QtWidgets.QComboBox(self.groupBox)
        self.cbnivel.setGeometry(QtCore.QRect(80, 130, 111, 22))
        self.cbnivel.setObjectName("cbnivel")
        self.cbnivel.addItem("")
        self.cbnivel.addItem("")
        self.cbnivel.addItem("")
        self.cbnivel.addItem("")
        self.cbnivel.addItem("")
        self.cbnivel.addItem("")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "GroupBox"))
        self.btadicionar.setText(_translate("Dialog", "adicionar"))
        self.label.setText(_translate("Dialog", "seu nome"))
        self.btexcluir.setText(_translate("Dialog", "Excluir"))
        self.btfechar.setText(_translate("Dialog", "fechar"))
        self.btordenar.setText(_translate("Dialog", "Ordenar"))
        self.pushButton.setText(_translate("Dialog", "Verificar"))
        self.label_2.setText(_translate("Dialog", "Total"))
        self.label_5.setText(_translate("Dialog", "Idade"))
        self.label_6.setText(_translate("Dialog", "Sexo"))
        self.rb1.setText(_translate("Dialog", "Masculuno"))
        self.rb2.setText(_translate("Dialog", "Feminino"))
        self.label_7.setText(_translate("Dialog", "Escolaridade"))
        self.cbnivel.setItemText(0, _translate("Dialog", "Sem escolaridade"))
        self.cbnivel.setItemText(1, _translate("Dialog", "Fundamental"))
        self.cbnivel.setItemText(2, _translate("Dialog", "Ensino Médio"))
        self.cbnivel.setItemText(3, _translate("Dialog", "Pos-graduação"))
        self.cbnivel.setItemText(4, _translate("Dialog", "Mestrado"))
        self.cbnivel.setItemText(5, _translate("Dialog", "Doutorado"))
